name: contacts_buddy

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  animations:
  cupertino_icons:
  flutter_easyloading:
  flutter_polyline_points: ^2.0.0
  flutter_spinkit:
  gap: ^3.0.1
  permission_handler: ^11.0.1
  provider:
  shimmer_animation:
  toggle_switch:
  sqflite:
  sqflite_common_ffi:
  url_launcher: ^6.2.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  test: ^1.24.9


flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/
